//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Game.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on Gabriele Cirulli&apos;s 2048 game..
        /// </summary>
        public static string AboutBasedOn {
            get {
                return ResourceManager.GetString("AboutBasedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give us a review.
        /// </summary>
        public static string AboutGiveUsAReview {
            get {
                return ResourceManager.GetString("AboutGiveUsAReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join numbers and get the 2048 tile!.
        /// </summary>
        public static string AboutJoinNumbers {
            get {
                return ResourceManager.GetString("AboutJoinNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use arrow keys to move the tiles..
        /// </summary>
        public static string AboutUseArrowKeys {
            get {
                return ResourceManager.GetString("AboutUseArrowKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When two tiles with the same number touch, they merge into one..
        /// </summary>
        public static string AboutWhenTwoNumberTouch {
            get {
                return ResourceManager.GetString("AboutWhenTwoNumberTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do you really want to restart current game?.
        /// </summary>
        public static string AreYouShureToRestart {
            get {
                return ResourceManager.GetString("AreYouShureToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to best scores.
        /// </summary>
        public static string BestScore {
            get {
                return ResourceManager.GetString("BestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we have no best scores yet.
        /// </summary>
        public static string BestScoreEmpty {
            get {
                return ResourceManager.GetString("BestScoreEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to best score!.
        /// </summary>
        public static string BestScoreToast {
            get {
                return ResourceManager.GetString("BestScoreToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use swipe gestures to move tiles.
        /// </summary>
        public static string ControlUseSwipe {
            get {
                return ResourceManager.GetString("ControlUseSwipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game over!.
        /// </summary>
        public static string GameGameOver {
            get {
                return ResourceManager.GetString("GameGameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I scored {0} points at 2048 for Windows Phone, a game where you join numbers to score high! #2048game #wp2048.
        /// </summary>
        public static string GameShareTemplate {
            get {
                return ResourceManager.GetString("GameShareTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You win!.
        /// </summary>
        public static string GameYouWin {
            get {
                return ResourceManager.GetString("GameYouWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keep playing.
        /// </summary>
        public static string OverKeepPlaying {
            get {
                return ResourceManager.GetString("OverKeepPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset.
        /// </summary>
        public static string OverReset {
            get {
                return ResourceManager.GetString("OverReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share result.
        /// </summary>
        public static string OverShareResult {
            get {
                return ResourceManager.GetString("OverShareResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to score:.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game control.
        /// </summary>
        public static string SettingsGameControl {
            get {
                return ResourceManager.GetString("SettingsGameControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use swipe gestures.
        /// </summary>
        public static string SettingsUseSwipe {
            get {
                return ResourceManager.GetString("SettingsUseSwipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show game field.
        /// </summary>
        public static string ShowGameField {
            get {
                return ResourceManager.GetString("ShowGameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
